version: "3"
networks:
  bot:

services:
  postgres:
    image: postgres:16-alpine3.18
    container_name: postgresql_bot
    restart: always
    tty: true
    volumes:
      - "/var/lib/data/bot/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: "$POSTGRES_DB"
    networks:
      - bot

  python:
    build:
      context: .
      dockerfile: Python.Dockerfile
    command: python3 bonzoboot.py
    volumes:
      - ./:/home/bonzo
    container_name: bonzo_py
    restart: always
    depends_on:
      - java
      - postgres
    networks:
      - bot

  java:
    build:
      context: .
      dockerfile: Java.Dockerfile
    container_name: lavalink
    restart: always
    expose:
      - 2333
    ports:
      - 2333:2333
    volumes:
      - ./lavalink:/home/lavalink
    networks:
      - bot
